const carOptions = [
  {
    id: 1,
    type: "SEDAN",
  },
  {
    id: 2,
    type: "SUV's"
  }
]

const sedans = [
  {
    id: 1,
    brand: "Mitsubishi",
    model: "Lancer",
    color: "Red",
    year: "2015",
    ac: "Yes",
    transmission: "Automatic",
    fuel: "Diesel",
    price: "1,400.00",
  },
  {
    id: 2,
    brand: "Toyota",
    model: "Vios",
    color: "White",
    year: "2017",
    ac: "Yes",
    transmission: "Manual",
    fuel: "Diesel",
    price: "1,400.00",
  },
  {
    id: 3,
    brand: "Honda",
    model: "Civic",
    color: "Red",
    year: "2017",
    ac: "Yes",
    transmission: "Automatic",
    fuel: "Diesel",
    price: "1,600.00",
  },
  {
    id: 4,
    brand: "Audi",
    model: "A4",
    color: "Grey",
    year: "2015",
    ac: "Yes",
    transmission: "Automatic",
    fuel: "Unleaded",
    price: "2,000.00",
  },
  {
    id: 5,
    brand: "Toyota",
    model: "Camry",
    color: "Matte Grey",
    year: "2017",
    ac: "Yes",
    transmission: "Automatic",
    fuel: "Unleaded",
    price: "2,000.00",
  },
  {
    id: 6,
    brand: "BMW",
    model: "M5",
    color: "White",
    year: "2018",
    ac: "Yes",
    transmission: "Manual",
    fuel: "Diesel",
    price: "2,500.00",
  },
  {
    id: 7,
    brand: "Ford",
    model: "Fusion",
    color: "Marine Blue",
    year: "2015",
    ac: "Yes",
    transmission: "Manual",
    fuel: "Unleaded",
    price: "2,700.00",
  },
  {
    id: 8,
    brand: "Toyota",
    model: "Corolla",
    color: "Silver",
    year: "2016",
    ac: "Yes",
    transmission: "Automatic",
    fuel: "Unleaded",
    price: "1,400.00",
  },
];

const suvs = [
  {
    id: 1,
    brand: "Toyota",
    model: "Fortuner",
    color: "Platinum White",
    year: "2015",
    ac: "Yes",
    transmission: "Manual",
    fuel: "Diesel",
    price: "3,300.00",
  },
  {
    id: 2,
    brand: "Hyundai",
    model: "Tucson",
    color: "French Blue",
    year: "2019",
    ac: "Yes",
    transmission: "Automatic",
    fuel: "Unleaded",
    price: "3,000.00",
  },
  {
    id: 3,
    brand: "Toyota",
    model: "Innova",
    color: "Grey",
    year: "2016",
    ac: "Yes",
    transmission: "Manual",
    fuel: "Diesel",
    price: "3,600.00",
  },

  {
    id: 4,
    brand: "Mitsubishi",
    model: "Xpander",
    color: "Dark Grey",
    year: "2018",
    ac: "Yes",
    transmission: "Automatic",
    fuel: "Diesel",
    price: "4,200.00",
  },
  {
    id: 5,
    brand: "Toyota",
    model: "Prado",
    color: "Red",
    year: "2015",
    ac: "Yes",
    transmission: "Automatic",
    fuel: "Diesel",
    price: "4,200.00",
  },
];

export { carOptions, sedans, suvs };
